### ISSUE TITLE
Redshift is quite slow for writing

### ISSUE THREAD

**Issue by vadym-kudenchuk-epam** [ObserveRTC/observer#67]
I should reduce buffer maxItems to 50 and after that connector continued send messages to Redshift.
```      
    buffer:
        maxItems: 50
        maxWaitingTimeInS: 10
```

**Comment by balazskreith** [comment]
This issue is rather for the connector project, as the observer does not have a direct connector to redshift.

The connector project uses JOOQ, and the redshift JDBC driver to insert data to redshift. There is a bulk insert we apply at the sink point, in which the size of the query size (and therefore the number of rows the connector commands RS to insert) depends on the size of the buffer. From the connector point of view by using this configuration it seems the bottleneck is at redshift.

After doing some research about the possible solution to improve the performance for redshift I would recommend to read [this](https://forums.pentaho.com/threads/150447-Slow-insertion-in-Amazon-Redshift-with-Table-Output-step/) thread. It says: 

> 1. Enable lazy conversion.
> 2. Create multiple copy of DB output, and the step where only transformation happening.
> 3. If you are using java script or any scripting, please avoid and replace with some other step.
> 4. Increase data buffer I/O size.

Another solution is to use an S3 bucket with a CSV output. That is possible by developing a CSVSink for the connector, but also requires integration between the redshift and the S3 bucket.

**Comment by balazskreith** [comment]
As a closing sentence here, and because I faced the problem with the new observer version as well, I can confidently say redshift is not designed for bulk insert and this is why it was slow.

Instead, there is a Firehose sink you can configure. The observer can directly put data to Firehose, which is designed to bulk load into redshift.
